### ISSUE TITLE
MemorySanitizer: use-of-uninitialized-value

### ISSUE THREAD

**Issue by rianquinn** [fmtlib/fmt#1399]
I get the following when using Clang's memory sanitizer:

```
==122794==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x4cb532 in fmt::v6::internal::buffer<char>::reserve(unsigned long) /usr/local/include/fmt/core.h:614:9
    #1 0x4d1945 in fmt::v6::internal::buffer<char>::resize(unsigned long) /usr/local/include/fmt/core.h:605:5
    #2 0x4d185c in fmt::v6::internal::buffer<char>::value_type* fmt::v6::internal::reserve<fmt::v6::internal::buffer<char>, 0>(std::back_insert_iterator<fmt::v6::internal::buffer<char> >&, unsigned long) /usr/local/include/fmt/format.h:288:5
    #3 0x4e8763 in void fmt::v6::internal::basic_writer<fmt::v6::buffer_range<char> >::write_decimal<unsigned long long>(unsigned long long) /usr/local/include/fmt/format.h:1440:9
    #4 0x4ce6bb in std::back_insert_iterator<fmt::v6::internal::buffer<char> > fmt::v6::internal::arg_formatter_base<fmt::v6::buffer_range<char>, fmt::v6::internal::error_handler>::operator()<unsigned long long, 0>(unsigned long long) /usr/local/include/fmt/format.h:1867:15
    #5 0x4ccd07 in fmt::v6::format_handler<fmt::v6::arg_formatter<fmt::v6::buffer_range<char> >, char, fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >::on_replacement_field(char const*) /usr/local/include/fmt/format.h:3255:9
    #6 0x4cc16a in void fmt::v6::internal::parse_format_string<false, char, fmt::v6::format_handler<fmt::v6::arg_formatter<fmt::v6::buffer_range<char> >, char, fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >&>(fmt::v6::basic_string_view<char>, fmt::v6::format_handler<fmt::v6::arg_formatter<fmt::v6::buffer_range<char> >, char, fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >&) /usr/local/include/fmt/format.h:2546:15
    #7 0x526ef1 in fmt::v6::buffer_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>::iterator fmt::v6::internal::vformat_to<char>(fmt::v6::internal::buffer<char>&, fmt::v6::basic_string_view<char>, fmt::v6::basic_format_args<fmt::v6::buffer_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >) (/home/user/working/build/tests/test_autosar_compliant_1+0x526ef1)
    #8 0x511af8 in fmt::v6::vprint(_IO_FILE*, fmt::v6::basic_string_view<char>, fmt::v6::format_args) (/home/user/working/build/tests/test_autosar_compliant_1+0x511af8)
    #9 0x4c90f1 in void fmt::v6::print<char [15], unsigned long&, char const*&, 0>(char const (&) [15], unsigned long&, char const*&) /usr/local/include/fmt/core.h:1497:3
    #10 0x4c8d3e in bsl::check_results() /home/user/working/bsl/tests/contracts/../../include/bsl/ut.h:267:13
    #11 0x4c3870 in main /home/user/working/bsl/tests/contracts/autosar_compliant_1.cpp:111:12
    #12 0x7f0edecc11a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)
    #13 0x44678d in _start (/home/user/working/build/tests/test_autosar_compliant_1+0x44678d)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/local/include/fmt/core.h:614:9 in fmt::v6::internal::buffer<char>::reserve(unsigned long)
Exiting
```

**Comment by vitaut** [comment]
Please provide an example to reproduce the sanitizer warning.

**Comment by rianquinn** [comment]
``` cmake
cmake_minimum_required(VERSION 3.13)
project(repro CXX)

find_package(fmt)
set(CMAKE_CXX_STANDARD 17)

set(CMAKE_CXX_FLAGS_MSAN "-fsanitize=memory -fPIE -pie")
set(CMAKE_LINKER_FLAGS_MSAN "-fsanitize=memory -fPIE -pie")

add_executable(repro main.cpp)
target_link_libraries(repro fmt::fmt)
```
```c++

#include <fmt/core.h>
#include <fmt/color.h>

auto
main() -> int
{
    fmt::print(fmt::fg(fmt::terminal_color::bright_green), "{:=^80}\n", "=");
    fmt::print("test");
}
```
```
[~/working/repro/build]: ./repro 
================================================================================
==21154==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x558724279b6e  (/home/rianquinn/working/repro/build/repro+0xc3b6e)
    #1 0x55872428c4f2  (/home/rianquinn/working/repro/build/repro+0xd64f2)
    #2 0x55872428c34b  (/home/rianquinn/working/repro/build/repro+0xd634b)
    #3 0x55872427dd3e  (/home/rianquinn/working/repro/build/repro+0xc7d3e)
    #4 0x55872427d6f9  (/home/rianquinn/working/repro/build/repro+0xc76f9)
    #5 0x55872427c040  (/home/rianquinn/working/repro/build/repro+0xc6040)
    #6 0x558724349041  (/home/rianquinn/working/repro/build/repro+0x193041)
    #7 0x5587243336e0  (/home/rianquinn/working/repro/build/repro+0x17d6e0)
    #8 0x55872427478f  (/home/rianquinn/working/repro/build/repro+0xbe78f)
    #9 0x558724274282  (/home/rianquinn/working/repro/build/repro+0xbe282)
    #10 0x7fcfb6ed71a2  (/lib64/libc.so.6+0x271a2)
    #11 0x5587241f773d  (/home/rianquinn/working/repro/build/repro+0x4173d)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/rianquinn/working/repro/build/repro+0xc3b6e) 
Exiting
```

**Comment by rianquinn** [comment]
This is with the latest {fmt} library, and I used the following to configure the build system:
```
CXX="clang++" cmake .. -DCMAKE_BUILD_TYPE=MSAN
```

**Comment by rianquinn** [comment]
This has to be a false positive. I can not see in the code how this error is true, and when I compile with the header-only approach, the problem goes away
