### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#319]
Remaining things to update on http://fmtlib.net

- [x] Downloads (also 3.0 download on github)
- [x] Links to older releases
- [x] Use the same theme for all releases

**Comment by nabijaczleweli** [comment]
Use `- [ ]` to make neat checkboxes

**Comment by vitaut** [comment]
Mostly done, but building docs for versions 1.0 and 1.1 gives an exception:

```
Exception occurred:
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/domains/cpp.py", line 4112, in _resolve_xref_inner
    assert parentSymbol  # should be there
AssertionError
```

Full stack trace:

```
Traceback (most recent call last):
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-pack
ages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 366, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/environment.py", line 1242, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/environment.py", line 1497, in resolve_references
    typ, target, node, contnode)
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/domains/cpp.py", line 4143, in resolve_xref
    target, node, contnode)[0]
  File "/home/viz/workspace/fmt/support/virtualenv/local/lib/python2.7/site-packages/sphinx/domains/cpp.py", line 4112, in _resolve_xref_inner
    assert parentSymbol  # should be there
AssertionError
```

The problem is caused by an unresolved reference to `std::string` in

```rst
    Constructs a string reference from an `std::string` object.
```

**Comment by vitaut** [comment]
Reported the assertion to Sphinx: https://github.com/sphinx-doc/sphinx/issues/2536

**Comment by vitaut** [comment]
The error is triggered by this directive:

```rst
.. doxygenfunction:: format(StringRef, ArgList)
```

**Comment by vitaut** [comment]
Fixed in Sphinx and https://github.com/fmtlib/fmt/commit/e68836c123551240cd539b8e5b05603340948f0a (to prevent pip from downgrading the package).

**Comment by vitaut** [comment]
Now there are some warnings when building docs for version 1.0:

```
Warning
doxygenfunction: Unable to resolve multiple matches for function “print” with arguments (std::ostream &, StringRef, ArgList) in doxygen xml output for project “format” from directory: /home/viz/workspace/fmt/support/doxyxml. Potential matches:

- template <typename... *Args*>
  void fmt::print(StringRef, const Args&...)
- template <typename... *Args*>
  void fmt::print(std::FILE *, StringRef, const Args&...)
- template <typename... *Args*>
  void fmt::print(std::ostream&, StringRef, const Args&...)
- void fmt::print(StringRef, ArgList)
- void fmt::print(std::FILE *, StringRef, ArgList)
- void fmt::print(std::ostream&, StringRef, ArgList)
```

**Comment by vitaut** [comment]
And one more at http://fmtlib.net/1.1.0/api.html#_CPPv2N3fmt3fmt4hexuEi
