### ISSUE TITLE
DOC doesn't build

### ISSUE THREAD

**Issue by yoooooooooooooooooooooooo** [fmtlib/fmt#786]
From Debian stable

        $ cmake .
        $ make doc
        ...
        The HTML pages are in html.
        TypeError: CleanCSS is not a function
            at Object.toCSS (/usr/lib/nodejs/less/lib/less/parser.js:620:32)
            at /usr/lib/nodejs/less/bin/lessc:357:32
            at Object.finish [as _finish] (/usr/lib/nodejs/less/lib/less/parser.js:669:28)
            at Object.subFinish [as _finish] (/usr/lib/nodejs/less/lib/less/import-visitor.js:63:47)
            at Object.subFinish [as _finish] (/usr/lib/nodejs/less/lib/less/import-visitor.js:63:47)
            at Object.subFinish [as _finish] (/usr/lib/nodejs/less/lib/less/import-visitor.js:63:47)
            at Object.tree.importVisitor.run (/usr/lib/nodejs/less/lib/less/import-visitor.js:25:22)
            at /usr/lib/nodejs/less/lib/less/import-visitor.js:72:38
            at fileParsedFunc (/usr/lib/nodejs/less/lib/less/parser.js:83:17)
            at /usr/lib/nodejs/less/lib/less/parser.js:106:29

**Comment by vitaut** [comment]
You need to install some dependencies, please see http://fmtlib.net/dev/usage.html#building-the-documentation
