### ISSUE TITLE
Undefined behaviour when formatting a long double

### ISSUE THREAD

**Issue by kivadiu** [fmtlib/fmt#903]
Formatting a long double requires `static_cast<double>` in the `write_double` function:
`internal::fputil::isnegative(static_cast<double>(value)))`.
If the `value` is larger than a `double`, this is undefined behaviour and crashes with the sanitizer:
```
#include <iostream>
#include <limits>
#include <fmt/format.h>

int main() {
  const auto v =
      static_cast<long double>(std::numeric_limits<double>::max()) * 2.L;
  std::cout << fmt::format("{}", v);
  return 0;
}
```

fails with this error compiled with clang++ 6.0:
```
Libraries/fmt/format.h:2843:56: runtime error: 3.59539e+308 is outside the range of representable values of type 'double'
    #0 0x40bfa1 in void fmt::v5::basic_writer<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >::write_double<long double>(long double, fmt::v5::basic_format_specs<char> const&) /home/fred/Devel/Delypse/Libraries/fmt/format.h:2843:56
    #1 0x3bcfd1 in _ZN3fmt2v58internal18arg_formatter_baseINS0_17back_insert_rangeINS1_12basic_bufferIcEEEEEclIeEENSt9enable_ifIXsr3std17is_floating_pointIT_EE5valueESt20back_insert_iteratorIS5_EE4typeESA_ /home/fred/Devel/Delypse/Libraries/fmt/format.h:1570:13
    #2 0x3b99b8 in fmt::v5::internal::result_of<fmt::v5::arg_formatter<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > > (int)>::type fmt::v5::visit<fmt::v5::arg_formatter<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >, fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >(fmt::v5::arg_formatter<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >&&, fmt::v5::basic_format_arg<fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >) /home/fred/Devel/Delypse/Libraries/fmt/format.h:1224:12
    #3 0x3af0af in fmt::v5::format_handler<fmt::v5::arg_formatter<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >, char, fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >::on_replacement_field(fmt::v5::internal::null_terminating_iterator<char>) /home/fred/Devel/Delypse/Libraries/fmt/format.h:3322:24
    #4 0x3ab13c in void fmt::v5::internal::parse_format_string<fmt::v5::internal::null_terminating_iterator<char>, fmt::v5::format_handler<fmt::v5::arg_formatter<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >, char, fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >&>(fmt::v5::internal::null_terminating_iterator<char>, fmt::v5::format_handler<fmt::v5::arg_formatter<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >, char, fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >&) /home/fred/Devel/Delypse/Libraries/fmt/format.h:2161:15
    #5 0x3a9b0e in fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char>::iterator fmt::v5::vformat_to<fmt::v5::arg_formatter<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >, char, fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >(fmt::v5::arg_formatter<fmt::v5::back_insert_range<fmt::v5::internal::basic_buffer<char> > >::range, fmt::v5::basic_string_view<char>, fmt::v5::basic_format_args<fmt::v5::basic_format_context<std::back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >) /home/fred/Devel/Delypse/Libraries/fmt/format.h:3353:3
    #6 0x3a1d8c in fmt::v5::vformat_to(fmt::v5::internal::basic_buffer<char>&, fmt::v5::basic_string_view<char>, fmt::v5::format_args) /home/fred/Devel/Delypse/Libraries/fmt/format.h:3457:10
    #7 0x39ffbd in fmt::v5::vformat[abi:cxx11](fmt::v5::basic_string_view<char>, fmt::v5::format_args) /home/fred/Devel/Delypse/Libraries/fmt/format.h:3593:3
    #8 0x4b263e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v5::format<long double>(fmt::v5::basic_string_view<char>, long double const&) /home/fred/Devel/Delypse/Libraries/fmt/core.h:1271:10
    #9 0x4b20d2 in main /home/fred/Devel/Delypse/Progs/test-fmt-long-double.cpp:8:16
    #10 0x7fdb6cf4111a in __libc_start_main (/lib64/libc.so.6+0x2311a)
    #11 0x29c029 in _start (/build/fred/Delypse/clang-sanitizer/bin/test-fmt-long-double+0x29c029)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior Libraries/fmt/format.h:2843:56 in 
```

I use version 5.1.0 but I see that in current git revision (61f81a071966fac324a7c10ea2310aea1371ac7a), `isnegative` is still implemented only for `double` (`format.h:350`). Why not as a template?

My compile flags for clang++ 6:
`-std=c++14 -fsanitize=address,undefined -fsanitize-address-use-after-scope -fno-sanitize-recover=address,undefined`
My link flags:
`-fsanitize=address,undefined -fsanitize-address-use-after-scope -fno-sanitize-recover=address,undefined`
I am on linux x86_64.

**Comment by vitaut** [comment]
Good catch. That's an artefact of supporting legacy compilers, removed in https://github.com/fmtlib/fmt/commit/57983423c37f49bfe9d2840c564af6b60231b359. Thanks for reporting.

**Comment by kivadiu** [comment]
It works now. Thank you :=)
